#!/bin/sh
# Postinstall script.
# - installs the root CA for .eth domains.
set -ex

# https://macinstallers.blogspot.com/2012/07/scripting-in-installer-packages.html


# Add the Dappnet root CA to the system Keychain for macOS.
# This CA signs all *.eth domains.

export CERT=./cert
cat > $CERT <<- EOM
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgIUSmu6CoAhVXkrNFmCOM4ti/fmW9MwDQYJKoZIhvcNAQEL
BQAwSjELMAkGA1UEBhMCVVMxGDAWBgNVBAoMD19EZXZlbG9wbWVudCBDQTEhMB8G
A1UEAwwYRGV2ZWxvcG1lbnQgY2VydGlmaWNhdGVzMB4XDTIyMDkwNTA2MDIyNVoX
DTMyMDkwMjA2MDIyNVowSjELMAkGA1UEBhMCVVMxGDAWBgNVBAoMD19EZXZlbG9w
bWVudCBDQTEhMB8GA1UEAwwYRGV2ZWxvcG1lbnQgY2VydGlmaWNhdGVzMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA17Hz/be4UWSLy2Td+kjHxbxzFRvu
7Duy3K8VX1txP/AzOivv/uph7IHOz+ZRTDu2aW2B0sf/rRruxkhz6HTHiILTXOBv
4Qoi8qzX1SoVE+tSnWWYkGTWhrNMaYZa58MkAanq2rDG2JpH0skI2uTQfGFYPiXR
vBOTmts/ORHaDY1QnAbzH6H05+GLdCjhwJ8fJic/twVlEdiqVxTNpyT37gGmyuPO
u2/YLASj2RPPlXH1RQn5SoRS+JGWwCUnlHrJYCoJN+BIjs88BK5PczqSaiFcVUGw
jSbYNGSKN+Zw4PV/3n4MZyD6JTU1uRDcSmCJefbxH06akkjQHdobrIk7cQIDAQAB
o1MwUTAdBgNVHQ4EFgQUKcX8QkSm3s35w/NNrwoQLqTju7UwHwYDVR0jBBgwFoAU
KcX8QkSm3s35w/NNrwoQLqTju7UwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAUSmp6gpy8tiKV2+/ax/Q6cI7i4aWvYDxIKP0EhN4AYHbYCfdThCv
LEveXh6z6yFvoDVMoYWZ85L6GnOz3wpe7myUvU8+ZUJVMpr9KQzqvHqPhsvo3832
T5/k8jt6lv0VsxiCojltC8cwkbhBzt6BNrW9DG9NWE4/F++KGQtezss6U7FTvqKj
MXl8XnC+IZVVHLDXQK+kp58twfomt3Q+IXJuItECZGfQGv8xTQEjNLSR7lTgPktO
hMdL2bUL9TE0BeVZahnyRKtrTtxSKwGTlIBDb7Xg5MFK0TkKJE7hOpipOFV2GgNY
ndkUFD+ToIwa+KmQb+LUMsBhQ9ZcYwYI+g==
-----END CERTIFICATE-----
EOM

# osascript -e 'display alert "Dappnet installation!" message "longer text can be added in the message field and it will be all shown on the pop-up alert."'

# This is verified to work on macOS 12.5.1 (21G83).
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $CERT
sudo security verify-cert -c $CERT
